/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01;

/**
 *
 * @author Guga
 */

import javax.swing.JOptionPane;
import static trabalho01.CadastroCliente.cl;
import static trabalho01.CadastroCliente.i;
import static trabalho01.CadastroProduto.j;
import static trabalho01.CadastroProduto.prn;
import static trabalho01.CadastroProduto.pri;
import static trabalho01.CadastroProduto.k;
public class Compra extends javax.swing.JFrame {
    public static Venda venda[] = new Venda[100];
    public static int l;

    /**
     * Creates new form Compra
     */
    public Compra() {
        initComponents();
         for( c = 0; c<i;c++){
           
        CbCliente.addItem(cl[c].getNome());
       }
    for( contp= 0; contp<j;contp++){
            
        CbCliente.addItem(prn[contp].getDescricao());
       } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String  tipopgto, nome, prod,nCompra,cheque,cartao;
    int  contp,c;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CbCliente = new javax.swing.JComboBox();
        CbPagamento = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CbProduto = new javax.swing.JComboBox();
        btnSalvar = new javax.swing.JButton();
        chImportado = new javax.swing.JRadioButton();
        chNacional = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        TbQnt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbClienteActionPerformed(evt);
            }
        });

        CbPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "cheque", "cartão" }));
        CbPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPagamentoActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Compra");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        chImportado.setText("Importado");
        chImportado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chImportadoActionPerformed(evt);
            }
        });

        chNacional.setText("Nacional");
        chNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNacionalActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente");

        TbQnt.setText("1");
        TbQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbQntActionPerformed(evt);
            }
        });

        jLabel5.setText("quantidade");

        jLabel2.setText("pagamento");

        jLabel7.setText("Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(CbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(68, 68, 68)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnSalvar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chNacional)
                            .addComponent(chImportado))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(TbQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TbQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chImportado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chNacional, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(jButton2))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (((String)CbCliente.getSelectedItem()).equals("")){
          JOptionPane.showMessageDialog(null, "Selecione um cliente para salvar");
         CbCliente.requestFocus();
     }
     else if (((String)CbProduto.getSelectedItem()).equals("")){
          JOptionPane.showMessageDialog(null, "Selecione um produto para salvar");
         CbCliente.requestFocus();
     }
       else if (TbQnt.getText() == null  ||TbQnt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade antes de salvar!!");
            TbQnt.requestFocus();
        }
      
       
       else{
           
        nome = (String) CbCliente.getSelectedItem();
        for( c = 0; c<i;c++){
           
           if(nome ==(String) cl[c].getNome()){
                break;
           }
       }
        prod = (String) CbProduto.getSelectedItem();
       if(chNacional.isSelected()){ 
             for( contp = 0; contp<j;contp++){
           
           if(prod ==(String) prn[contp].getDescricao()){
                if(cheque!= null){
                 tipopgto="cheque";
                 Cheque  ch = new Cheque(tipopgto,nome,cheque);
                  venda[l] = new Venda( l, cl[c],prn[contp],l,ch);
                  JOptionPane.showMessageDialog(null, "Salvo com sucesso!!");
                  l++;
                }
                else if(cartao!= null){
                  tipopgto = "cartao";
                  Cartao  ct = new Cartao(tipopgto,nome,cartao);
                  venda[l] = new Venda( l, cl[c],pri[contp],l,ct);
                  JOptionPane.showMessageDialog(null, "Salvo com sucesso!!");
                  l++;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro no pagamento!!");
                }
                break;
                     }
                 }
            }
      
       else if(chImportado.isSelected()){
            for( contp = 0; contp<k;contp++){
           
           if(prod ==(String) pri[contp].getDescricao()){
                   if(cheque!= null){
                 tipopgto="cheque";
                 Cheque  ch = new Cheque(tipopgto,nome,cheque);
                  venda[l] = new Venda( l, cl[c],prn[contp],l,ch);
                  JOptionPane.showMessageDialog(null, "Salvo com sucesso!!");
                  l++;
                }
                else if(cartao!= null){
                  tipopgto = "cartao";
                  Cartao  ct = new Cartao(tipopgto,nome,cartao);
                  venda[l] = new Venda( l, cl[c],pri[contp],l,ct);
                  l++;
                  JOptionPane.showMessageDialog(null, "Salvo com sucesso!!");
                }
                else{
                    JOptionPane.showMessageDialog(null, "Erro no pagamento!!");
                }
                break;
           }
           else{
               JOptionPane.showMessageDialog(null, "Erro na descricao do produto!!");
           }
          
       }
       
       
       
       }
        
       }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void chImportadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chImportadoActionPerformed
     CbProduto.removeAllItems();
        if(chNacional.isSelected()){
            chNacional.setSelected(false);
        }
        for( contp= 0; contp<k;contp++){
            
        CbProduto.addItem(pri[contp].getDescricao());
    }                // TODO add your handling code here:
    }//GEN-LAST:event_chImportadoActionPerformed

    private void chNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNacionalActionPerformed
        CbProduto.removeAllItems();
       if(chImportado.isSelected()){
            chImportado.setSelected(false);
        }
        for( contp= 0; contp<j;contp++){
            
        CbProduto.addItem(prn[contp].getDescricao());
       } 
    }//GEN-LAST:event_chNacionalActionPerformed

    private void CbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbClienteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuInicial form2 = new MenuInicial();
            form2.setVisible(true);
            
     
            dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TbQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbQntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TbQntActionPerformed

    private void CbPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPagamentoActionPerformed
         if (((String)CbPagamento.getSelectedItem()).equals("Cheque")){
            cheque =null;
            cartao = null;
            cheque = JOptionPane.showInputDialog(" insira o Numero de serie do cheque ");
        }
        else if (((String)CbPagamento.getSelectedItem()).equals("Cartão")){
             cheque =null;
            cartao = null;
            cartao = JOptionPane.showInputDialog(" insira o Numero do cartao ");
        }
    }//GEN-LAST:event_CbPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra().setVisible(true);
            }
        });
    }
    void exportarContc1(int contC) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void exportarCont1(int contP) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbCliente;
    private javax.swing.JComboBox CbPagamento;
    private javax.swing.JComboBox CbProduto;
    private javax.swing.JTextField TbQnt;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JRadioButton chImportado;
    private javax.swing.JRadioButton chNacional;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
