/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01;

/**
 *
 * @author Guga
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import javax.swing.JOptionPane;

import static trabalho01.CadastroCliente.i;
import static trabalho01.CadastroCliente.cl;
import static trabalho01.CadastroProduto.prn;
import static trabalho01.CadastroProduto.pri;
import static trabalho01.CadastroProduto.j;
import static trabalho01.CadastroProduto.k;
import static trabalho01.Compra.venda;
import static trabalho01.Compra.l;

public class MenuInicial extends javax.swing.JFrame{

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastrar = new javax.swing.JButton();
        BtComprar = new javax.swing.JButton();
        BtRelatorio = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtCarregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        BtComprar.setText("Comprar");
        BtComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtComprarActionPerformed(evt);
            }
        });

        BtRelatorio.setText("Relatorios");
        BtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRelatorioActionPerformed(evt);
            }
        });

        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtCarregar.setText("Carregar");
        BtCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCarregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menu Inicial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(BtComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BtRelatorio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar)
                    .addComponent(BtCarregar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        MenuCadastrar form2 = new MenuCadastrar();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void BtComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtComprarActionPerformed
        Compra form2 = new Compra();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtComprarActionPerformed

    private void BtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRelatorioActionPerformed
        Relatorios form2 = new Relatorios();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtRelatorioActionPerformed
     
    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try {
            if(i!=0) {
                FileOutputStream cliente = new FileOutputStream("cliente.dat");
                ObjectOutputStream ocliente = new ObjectOutputStream(cliente);
                for(int j=0; j<i;j++){
                    ocliente.writeObject(cl[j]);
                }
                ocliente.flush();
                ocliente.close();
                ocliente.flush();
                ocliente.close();
            }
            if (j!=0) {
                FileOutputStream produton = new FileOutputStream("produton.dat");
                ObjectOutputStream oproduton = new ObjectOutputStream(produton);
                for(int i=0; i<j;i++){
                    oproduton.writeObject(prn[i]);
                }
                oproduton.flush();
                oproduton.close();
                oproduton.flush();
                oproduton.close();
            }
            if (k!=0) {
                FileOutputStream produtoi = new FileOutputStream("produtoi.dat");
                ObjectOutputStream oprodutoi = new ObjectOutputStream(produtoi);
                for(int i=0; i<k;i++){
                    oprodutoi.writeObject(pri[i]);
                }
                oprodutoi.flush();
                oprodutoi.close();
                oprodutoi.flush();
                oprodutoi.close();
            }
            if(l!=0) {
                FileOutputStream vendas = new FileOutputStream("vendas.dat");
                ObjectOutputStream ovendas = new ObjectOutputStream(vendas);
                for(int i=0; i<l;i++){
                    ovendas.writeObject(venda[i]);
                }
                ovendas.flush();
                ovendas.close();
                ovendas.flush();
                ovendas.close();
            }
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!!");
        }
        catch(IOException e){
        }
        
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCarregarActionPerformed
        try {
            FileInputStream cliente = new FileInputStream("cliente.dat");
            ObjectInputStream ocliente = new ObjectInputStream(cliente);
            for(int j=0; j<i;j++){
                cl[j] = (Cliente) ocliente.readObject();
            }
            ocliente.close();
            cliente.close();
          
            FileInputStream produton = new FileInputStream("produton.dat");
            ObjectInputStream oproduton = new ObjectInputStream(produton);
            for(int i=0; i<l;i++){
                prn[i] = (ProdutoNacional) oproduton.readObject();
            }
            oproduton.close();
            produton.close();

            FileInputStream produtoi = new FileInputStream("produtoi.dat");
            ObjectInputStream oprodutoi = new ObjectInputStream(produtoi);
            for(int i=0; i<k;i++){
                pri[i] = (ProdutoImportado) oprodutoi.readObject();
            }
            oprodutoi.close();
            produtoi.close();
            
            FileInputStream vendas = new FileInputStream("vendas.dat");
            ObjectInputStream ovendas = new ObjectInputStream(vendas);
            for(int i=0; i<l;i++){
                venda[i] = (Venda) ovendas.readObject();
            }
            ovendas.close();
            vendas.close();
    }
            
        catch(ClassNotFoundException | IOException e){
        }
        
        JOptionPane.showMessageDialog(null, "Dados carregados com sucesso");
    }//GEN-LAST:event_BtCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCarregar;
    private javax.swing.JButton BtComprar;
    private javax.swing.JButton BtRelatorio;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
