/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01;

/**
 *
 * @author Guga
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

import static trabalho01.CadastroCliente.i;
import static trabalho01.CadastroCliente.cl;
import static trabalho01.CadastroProduto.prn;
import static trabalho01.CadastroProduto.pri;
import static trabalho01.CadastroProduto.j;
import static trabalho01.CadastroProduto.k;

public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastrar = new javax.swing.JButton();
        BtComprar = new javax.swing.JButton();
        BtRelatorio = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtCarregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        BtComprar.setText("Comprar");
        BtComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtComprarActionPerformed(evt);
            }
        });

        BtRelatorio.setText("Relatorios");
        BtRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRelatorioActionPerformed(evt);
            }
        });

        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtCarregar.setText("Carregar");
        BtCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCarregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Menu Inicial");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(BtSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(BtComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtComprar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BtRelatorio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar)
                    .addComponent(BtCarregar))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        MenuCadastrar form2 = new MenuCadastrar();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void BtComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtComprarActionPerformed
        Compra form2 = new Compra();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtComprarActionPerformed

    private void BtRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRelatorioActionPerformed
        Relatorios form2 = new Relatorios();
        form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtRelatorioActionPerformed
     
    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        try {
            if(i!=0) {
                BufferedWriter cliente = new BufferedWriter(new FileWriter("cliente.txt", true));
                for (int l=0; l<i; l++) {
                    cliente.append(cl[l].getCpf() + "\n");
                    cliente.append(cl[l].getNome() + "\n");
                }
                cliente.close();
            }
            if (j!=0) {
                BufferedWriter produton = new BufferedWriter(new FileWriter("produton.txt", true));
                for (int l=0; l<j; l++) {
                    produton.append(prn[l].getCodigo() + "\n");
                    produton.append(prn[l].getDescricao() + "\n");
                    produton.append(prn[l].getValor() + "\n");
                    produton.append(prn[l].getTipoProduto()+ "\n");
                    produton.append(prn[l].getTaxaImposto()+ "\n");
                }
                produton.close();
            }
            if (k!=0) {
                BufferedWriter produtoi = new BufferedWriter(new FileWriter("produtoi.txt", true));
                for (int l=0; l<k; l++) {
                    produtoi.append(pri[l].getCodigo() + "\n");
                    produtoi.append(pri[l].getDescricao() + "\n");
                    produtoi.append(pri[l].getValor() + "\n");
                    produtoi.append(pri[l].getTipoProduto()+ "\n");
                    produtoi.append(pri[l].getTaxaImposto()+ "\n");
                }
                produtoi.close();
            }
            JOptionPane.showMessageDialog(null, "Dados salvos com sucesso!!");
        }
        catch(IOException io){
        }
        
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCarregarActionPerformed
        try {
            BufferedReader cliente = new BufferedReader(new FileReader("cliente.txt"));
            while(cliente.ready()){
               String Cpf = cliente.readLine();
               String Nome = cliente.readLine();
               cl[i].setCpf(Cpf);
               cl[i].setNome(Nome);
               i++;
            }   
                cliente.close();
            }
            catch(IOException e){
            }
            
        try {
            BufferedReader produton = new BufferedReader(new FileReader("produton.txt"));
            while(produton.ready()){
               String Cod = produton.readLine();
               String Nome = produton.readLine();
               float preco = Float.parseFloat(produton.readLine());
               String Tipo = produton.readLine();
               float taxa = Float.parseFloat(produton.readLine());
               prn[j].setCodigo(Cod);
               prn[j].setDescricao(Nome);
               prn[j].setValor(preco);
               prn[j].setTipoProduto(Tipo);
               prn[j].setTaxaImposto(taxa);
               j++;
            }
            produton.close();
        }
        catch(IOException e){
        }
        
        try {
            BufferedReader produtoi = new BufferedReader(new FileReader("produtoi.txt"));
            while(produtoi.ready()){
               String Cod = produtoi.readLine();
               String Nome = produtoi.readLine();
               float preco = Float.parseFloat(produtoi.readLine());
               String Tipo = produtoi.readLine();
               float taxa = Float.parseFloat(produtoi.readLine());
               float imports = Float.parseFloat(produtoi.readLine());
               pri[k].setCodigo(Cod);
               pri[k].setDescricao(Nome);
               pri[k].setValor(preco);
               pri[k].setTipoProduto(Tipo);
               pri[k].setTaxaImposto(taxa);
               pri[k].setTaxaImportacao(imports);
               k++;
            }
            produtoi.close();
        }
        catch(IOException e){
        }
    }//GEN-LAST:event_BtCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCarregar;
    private javax.swing.JButton BtComprar;
    private javax.swing.JButton BtRelatorio;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
