/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho01;

/**
 *
 * @author Erick Yoshike
 */
public class RelatoriosVendas extends javax.swing.JFrame {

    /**
     * Creates new form RelatoriosVendas
     */
    public RelatoriosVendas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vGeral = new javax.swing.JButton();
        vEspecifico = new javax.swing.JButton();
        vSimplificada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vDetalhada = new javax.swing.JButton();
        rVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Relatorios Vendas");

        vGeral.setText("Vendas Geral");
        vGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vGeralActionPerformed(evt);
            }
        });

        vEspecifico.setText("Vendas Especifico");
        vEspecifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vEspecificoActionPerformed(evt);
            }
        });

        vSimplificada.setText("Simplificada");
        vSimplificada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vSimplificadaActionPerformed(evt);
            }
        });

        jLabel2.setText("Vendas por tipo de pagamento:");

        vDetalhada.setText("Detalhada");
        vDetalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vDetalhadaActionPerformed(evt);
            }
        });

        rVoltar.setText("Voltar");
        rVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(vSimplificada)
                                .addGap(18, 18, 18)
                                .addComponent(vDetalhada))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(vGeral)
                                        .addGap(26, 26, 26)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(vEspecifico)
                        .addGap(138, 138, 138))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rVoltar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(vGeral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vEspecifico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vSimplificada)
                    .addComponent(vDetalhada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rVoltar)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vGeralActionPerformed
       VendasGeral form2 = new VendasGeral();
       form2.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_vGeralActionPerformed

    private void vDetalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vDetalhadaActionPerformed
      VendasDetalhadas form2 = new VendasDetalhadas();
       form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_vDetalhadaActionPerformed

    private void rVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rVoltarActionPerformed
        Relatorios form2 = new Relatorios();
        form2.setVisible(true);

        dispose();
    }//GEN-LAST:event_rVoltarActionPerformed

    private void vEspecificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vEspecificoActionPerformed
      VendaEspecifico form2 = new VendaEspecifico();
       form2.setVisible(true);
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_vEspecificoActionPerformed

    private void vSimplificadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vSimplificadaActionPerformed
      VendasSimplificada form2 = new VendasSimplificada();
       form2.setVisible(true);
        dispose();
    }//GEN-LAST:event_vSimplificadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatoriosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatoriosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatoriosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatoriosVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatoriosVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton rVoltar;
    private javax.swing.JButton vDetalhada;
    private javax.swing.JButton vEspecifico;
    private javax.swing.JButton vGeral;
    private javax.swing.JButton vSimplificada;
    // End of variables declaration//GEN-END:variables
}
